[package]
name = "rust_ray_tracer"
version = "0.2.0"
authors = ["peter-seres <peter.seres.ae@gmail.com>"]
edition = "2022"

[dependencies]
png = "0.17.7"
nalgebra = "0.31.4"
time = "*"

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 3